"""
Evaluation script to compute Dice coefficient on test set and visualize predictions.
"""

import torch
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from dataset import OASISDataset
from modules import UNet

def dice_coefficient(pred, target, num_classes):
    """Calculate the Dice coefficient for segmentation."""
    pred = torch.argmax(pred, dim=1)
    dice_scores = []
    for c in range(num_classes):
        pred_c = (pred == c)
        target_c = (target == c)
        intersection = (pred_c & target_c).float().sum()
        union = pred_c.float().sum() + target_c.float().sum()
        dice = (2.0 * intersection + 1e-8) / (union + 1e-8)
        dice_scores.append(dice)
    return torch.mean(torch.stack(dice_scores))


def evaluate_test_dice(model_path="best_model.pth", num_classes=3, dropout=0.1, batch_size=4, visualize_samples=5):
    """Evaluate the model on the test dataset and visualize some predictions."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load test dataset
    test_ds = OASISDataset(
        "keras_png_slices_test",
        "keras_png_slices_seg_test"
    )
    test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

    # Load trained model
    model = UNet(in_channels=1, num_classes=num_classes, dropout=dropout).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    total_dice = 0.0
    count = 0
    shown_images = 0

    all_imgs, all_masks, all_preds = [], [], []

    # Evaluate dice score on test set
    with torch.no_grad():
        for imgs, masks in test_loader:
            imgs, masks = imgs.to(device), masks.to(device)
            outputs = model(imgs)
            dice = dice_coefficient(outputs, masks, num_classes)
            total_dice += dice.item()
            count += 1

            # Collect images for visualization
            # This code was generated by ChatGPT
            if shown_images < visualize_samples:
                for i in range(imgs.size(0)):
                    all_imgs.append(imgs[i].cpu().squeeze())
                    all_masks.append(masks[i].cpu())
                    all_preds.append(torch.argmax(outputs[i], dim=0).cpu())
                    shown_images += 1
                    if shown_images >= visualize_samples:
                        break

    mean_dice = total_dice / count
    print(f"Mean Dice Coefficient on Test Set: {mean_dice:.4f}")

    # Plot samples
    if visualize_samples > 0:
        fig, axes = plt.subplots(visualize_samples, 3, figsize=(12, 4 * visualize_samples))
        for i in range(visualize_samples):
            axes[i, 0].imshow(all_imgs[i], cmap="gray")
            axes[i, 0].set_title("Input Image")
            axes[i, 1].imshow(all_masks[i], cmap="gray")
            axes[i, 1].set_title("Ground Truth")
            axes[i, 2].imshow(all_preds[i], cmap="gray")
            axes[i, 2].set_title("Predicted Mask")
            for j in range(3):
                axes[i, j].axis("off")

        plt.tight_layout()
        plt.show()

    return mean_dice


if __name__ == "__main__":
    evaluate_test_dice()